export type BuiltInToolType =
  | 'blockquote'
  | 'bold'
  | 'code'
  | 'clear'
  | 'emoji'
  | 'font-family'
  | 'font-size'
  | 'fullscreen'
  | 'headings'
  | 'hr'
  | 'italic'
  | 'letter-spacing'
  | 'line-height'
  | 'link'
  | 'numbered-list'
  | 'bulleted-list'
  | 'media'
  | 'redo'
  | 'remove-styles'
  | 'divider'
  | 'strike-through'
  | 'superscript'
  | 'subscript'
  | 'text-align'
  | 'text-color'
  | 'text-indent'
  | 'underline'
  | 'undo'
  | 'table'

export const LIST_TYPES = ['numbered-list', 'bulleted-list']
